AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda pipeline required file
Resources:
  index-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./Lambdas/LF1
      Description: 'Lambda function to upload photo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::837466521382:role/service-role/lambda-multirole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: put
  search-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./Lambdas/LF2
      Description: 'Lambda function to search photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::837466521382:role/service-role/lambda-multirole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: get
